### ISSUE TITLE
Add event programmatically

### ISSUE THREAD

**Issue by encryptgo** [myohei/ExtendedCalendarView#1]
How we add event programmatically ex: data from server. how we know the date in specific cell (ex: date 12 in cell 15).

**Comment by myohei** [comment]
You can add event like this.

```
int eventDate; // from server
ECCalendarCell v = (ECCalendarCell) extendedCalendarView.getCellView(12); // or your set custom cell class 
v. setTopText("YOUR EVENT");
```

**Comment by encryptgo** [comment]
Thanks you very much, you save my time.

**Comment by myohei** [comment]
You're Welcome!!

**Comment by encryptgo** [comment]
Sorry for asking you again, How to remove all event? when I go to next month all event label still there not automatically removed.
