### ISSUE TITLE
Clear Event on next month

### ISSUE THREAD

**Issue by encryptgo** [myohei/ExtendedCalendarView#2]
Sorry for asking you again, How to remove all event? when I go to next month all event label still there not automatically removed (customize cell view).

**Comment by myohei** [comment]
Sorry, my response is late.

This Library was updated.  changed  how to create Calendar Cell View.
Use Adapter like ListView. see [README](https://github.com/myohei/ExtendedCalendarView#usage).

**Comment by encryptgo** [comment]
Wow great! thanks very much @myohei

**Comment by myohei** [comment]
you're welcome!! 
Try it!!!!!!
